### ISSUE TITLE
Not Passing all 4 Builds After 3.6 Issue "Resolved"

### ISSUE THREAD

**Issue by Mross2858** [mikeizbicki/continuous-integration#34]
When I attempted to complete the homework after the python 3.6 issue was resolved, I still got an error message - is this happening to anyone else?

 I noticed my forked repo (? I don't know if that's the right terminology) still checks for python 3.6. I tried to fork again and make a new copy thinking that might work but github says I can only make one, so I tried deleting my continuous-integration folder and redoing the assignment but I still get the same error (I must note that all of my changes were still saved - I think it's because Its still the original forked repo?)

If anyone has found a solution please let me know!

**Comment by mikeizbicki** [comment]
The simplest way to "reset" your forked repo so that it matches the latest upstream on github is to

1. delete the repo from the lambda server, and
2. delete the fork from github in the web interface.

It sounds like you did (1) but not (2).

We'll be going over in class better ways of updating your repos later in class that don't involve completely restarting from scratch.
